language = "toml"

[commands]
[commands.architecture]
description = "Extracts all impls, structs, and imports to architecture/*.rs"
usage = "cargo invoke architecture [DIR] [OPTIONS]"
examples = [
    "cargo invoke architecture",
    "cargo invoke architecture my_crate_dir",
    "cargo invoke architecture --output custom_path",
]
[[commands.architecture.parameters]]
name = "[DIR]"
description = "Optional directory to process. Defaults to current directory."
[[commands.architecture.parameters]]
name = "--output <PATH>"
description = "Specifies the output directory for the generated files."

[commands.diff]
description = "Compares architecture outputs from two directories and generates a diff"
usage = "cargo invoke diff DIR1 DIR2"
examples = ["cargo invoke diff crate1 crate2"]
[[commands.diff.parameters]]
name = "DIR1"
description = "First directory to compare"
[[commands.diff.parameters]]
name = "DIR2"
description = "Second directory to compare"

[commands.diagram]
description = "Creates a mermaid diagram from a Rust file mapping struct relationships via function calls"
usage = "cargo invoke diagram <TARGET> [OPTIONS]"
examples = [
    "cargo invoke diagram src/lib.rs",
    "cargo invoke diagram src/main.rs --format png",
]
[[commands.diagram.parameters]]
name = "<TARGET>"
description = "Specifies the source Rust file to generate the diagram from."

[commands.view]
description = "Creates a png/svg from a mermaid diagram"
usage = "cargo invoke view <TARGET> [OPTIONS]"
examples = [
    "cargo invoke view src/lib.rs",
    "cargo invoke view src/main.rs --format png",
]
[[commands.view.parameters]]
name = "<TARGET>"
description = ""

[commands.connections]
description = "Generates a Mermaid diagram showing class relationships through function calls"
usage = "cargo invoke connections [OPTIONS]"
examples = ["cargo invoke connections"]
[[commands.connections.parameters]]
name = "[OPTIONS]"
description = ""

[commands.state_diagram]
description = "Generates a Mermaid diagram showing struct relationships through state transitions"
usage = "cargo invoke state_diagram [OPTIONS]"
examples = ["cargo invoke state_diagram"]
[[commands.state_diagram.parameters]]
name = "[OPTIONS]"
description = ""

[commands.class_diagram]
description = "Generates a Mermaid diagram showing class relationships through state transitions"
usage = "cargo invoke class_diagram [OPTIONS]"
examples = ["cargo invoke class_diagram"]
[[commands.class_diagram.parameters]]
name = "[OPTIONS]"
description = ""

[commands.view_class_diagram]
description = "Presents a Mermaid diagram showing class relationships through state transitions"
usage = "cargo invoke view_class_diagram [OPTIONS]"
examples = ["cargo invoke view_class_diagram"]
[[commands.view_class_diagram.parameters]]
name = "[OPTIONS]"
description = ""

[commands.view_connections]
description = "Presents a Mermaid diagram showing abbreviated class relationships through state transitions"
usage = "cargo invoke view_connections [OPTIONS]"
examples = ["cargo invoke view_connections"]
[[commands.view_connections.parameters]]
name = "[OPTIONS]"
description = ""
